server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: vault_audit_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: auditlogs
          __path__: /var/log/vault/vault-audit.log
  - job_name: vault_system_operational_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: systemlogs
          __path__: /var/log/vault/vault.log
